[build]
  # Directory base del progetto frontend
  base = "frontend/"
  
  # Comando di build per Vite
  command = "npm run build"
  
  # Directory di output per Vite (default: dist)
  publish = "dist"

# Configurazione per SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers per CORS e sicurezza
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers specifici per assets statici
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configurazione environment variables (opzionale)
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9" 